OPTIONS (
skip=1,
errors=0,
direct=true,
multithreading=true 
)
LOAD DATA
INFILE 'CHARTEVENTS.csv' "str '\n'"
BADFILE 'logfile.bad'
DISCARDFILE 'logfile.discard'
APPEND
INTO TABLE chartevents
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING nullcols
(
ROW_ID, 
SUBJECT_ID,
HADM_ID,
ICUSTAY_ID,
ITEMID,
CHARTTIME DATE "YYYY-MM-DD HH24:MI:SS",
STORETIME DATE "YYYY-MM-DD HH24:MI:SS",
CGID,
VALUE,
VALUENUM,
VALUEUOM,
WARNING,
ERROR,
RESULTSTATUS,
STOPPED
)