OPTIONS (
skip=1,
errors=0,
direct=true,
multithreading=true 
)
LOAD DATA
INFILE 'CPTEVENTS.csv' "str '\n'"
BADFILE 'logfile.bad'
DISCARDFILE 'logfile.discard'
APPEND
INTO TABLE cptevents
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING nullcols
(
ROW_ID, 
SUBJECT_ID,
HADM_ID,
COSTCENTER,
CHARTDATE DATE "YYYY-MM-DD HH24:MI:SS",
CPT_CD,
CPT_NUMBER,
CPT_SUFFIX,
TICKET_ID_SEQ,
SECTIONHEADER,
SUBSECTIONHEADER,
DESCRIPTION 
)