OPTIONS (
skip=1,
errors=0,
direct=true,
multithreading=true 
)
LOAD DATA
INFILE 'D_CPT.csv' "str '\n'"
BADFILE 'logfile.bad'
DISCARDFILE 'logfile.discard'
APPEND
INTO TABLE services
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING nullcols
(
ROW_ID, 
CATEGORY,
SECTIONRANGE,
SECTIONHEADER,
SUBSECTIONRANGE,
SUBSECTIONHEADER,
CODESUFFIX,
MINCODEINSUBSECTION,
MAXCODEINSUBSECTION
)