OPTIONS (
skip=1,
errors=0,
direct=true,
multithreading=true 
)
LOAD DATA
INFILE 'MICROBIOLOGYEVENTS.csv' "str '\n'"
BADFILE 'logfile.bad'
DISCARDFILE 'logfile.discard'
APPEND
INTO TABLE microbiologyevents
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING nullcols
(
ROW_ID,
SUBJECT_ID,
HADM_ID,
CHARTDATE DATE "YYYY-MM-DD HH24:MI:SS",
CHARTTIME DATE "YYYY-MM-DD HH24:MI:SS",
SPEC_ITEMID,
SPEC_TYPE_DESC,
ORG_ITEMID,
ORG_NAME,
ISOLATE_NUM,
AB_ITEMID,
AB_NAME,
DILUTION_TEXT,
DILUTION_COMPARISON,
DILUTION_VALUE,
INTERPRETATION
)
