-- ------------------------------------------------------------------
-- Title: Logistic Organ Dysfunction Score (LODS)
-- MIMIC version: MIMIC-III v1.4
-- Originally written as sofa.sql by: Alistair Johnson 
-- Edited as lods.sql by: Josh Gieringer
-- Contact: aewj [at] mit [dot] edu
-- Contact: joshua [dot] gieringer [at] digitalreasoning [dot] com
-- ------------------------------------------------------------------

-- This query extracts the logistic organ dysfunction score
-- This score is a measure of organ failure for patients in the ICU.
-- The score is calculated on the first day of each ICU patients' stay.
-- The score is calculated for *all* ICU patients, with the assumption that the user will subselect appropriate ICUSTAY_IDs.
-- For example, the score is calculated for neonates, but it is likely inappropriate to actually use the score values for these patients.

-- Reference for LODS:
-- Le Gall J, Klar J, Lemeshow S, et al. 
-- "The Logistic Organ Dysfunction System: A New Way to Assess Organ Dysfunction in the Intensive Care Unit."
-- JAMA. 1996;276(10):802-810. doi:10.1001/jama.1996.03540100046027. 

-- Variables used in LODS:
--  GCS, FiO2, Ventilation status (sourced from CHARTEVENTS)
--  Creatinine, Bilirubin, FiO2, PaO2, Platelets, Systolic Blood Pressure, 
--  Prothombin Time, Urea Nitrogen, Heart Rate (sourced from LABEVENTS)
--  Urine output (sourced from OUTPUTEVENTS)

-- The following views required to run this query:
--  1) uofirstday - generated by urine-output-first-day.sql
--  2) ventfirstday - generated by ventilated-first-day.sql
--  3) vitalsfirstday - generated by vitals-first-day.sql
--  4) gcsfirstday - generated by gcs-first-day.sql
--  5) labsfirstday - generated by labs-first-day.sql
--  6) bloodgasfirstdayarterial - generated by blood-gas-first-day-arterial.sql
--  7) echodata - generated by echo-data.sql
--  8) ventdurations - generated by ventilation-durations.sql

DROP MATERIALIZED VIEW IF EXISTS LODS;

CREATE MATERIALIZED VIEW LODS AS
with wt AS
(
  SELECT ie.icustay_id
    -- ensure weight is measured in kg
    , avg(CASE
        WHEN itemid IN (762, 763, 3723, 3580, 226512)
          THEN valuenum
        -- convert lbs to kgs
        WHEN itemid IN (3581)
          THEN valuenum * 0.45359237
        WHEN itemid IN (3582)
          THEN valuenum * 0.0283495231
        ELSE null
      END) AS weight

  from icustays ie
  left join chartevents c
    on ie.icustay_id = c.icustay_id
  WHERE valuenum IS NOT NULL
  AND itemid IN
  (
    762, 763, 3723, 3580,                     -- Weight Kg
    3581,                                     -- Weight lb
    3582,                                     -- Weight oz
    226512 -- Metavision: Admission Weight (Kg)
  )
  AND valuenum != 0
  and charttime between ie.intime - interval '1' day and ie.intime + interval '1' day
  group by ie.icustay_id
)
-- 5% of patients are missing a weight, but we can impute weight using their echo notes
, echo2 as(
  select ie.icustay_id, avg(weight * 0.45359237) as weight
  from icustays ie
  left join echodata echo
    on ie.hadm_id = echo.hadm_id
    and echo.charttime > ie.intime - interval '7' day
    and echo.charttime < ie.intime + interval '1' day
  group by ie.icustay_id
)
, pafi1 as
(
  -- join blood gas to ventilation durations to determine if patient was vent
  select bg.icustay_id, bg.charttime
  , PaO2FiO2
  , case when vd.icustay_id is not null then 1 else 0 end as IsVent
  from bloodgasfirstdayarterial bg
  left join ventdurations vd
    on bg.icustay_id = vd.icustay_id
    and bg.charttime >= vd.starttime
    and bg.charttime <= vd.endtime
  order by bg.icustay_id, bg.charttime
)
, pafi2 as
(
  select icustay_id
  , min(case when IsVent = 1 then PaO2FiO2 else null end) as PaO2FiO2_vent_min
  from pafi1
  group by icustay_id
)
-- Aggregate the components for the score
, scorecomp as
(
select ie.icustay_id
  , v.SysBP_Min
  , v.SysBP_Max
  , v.HeartRate_Min
  , v.HeartRate_Max

  , l.BUN_Max
  , l.Creatinine_Max
  , l.Bilirubin_Max
  , l.PT_Max
  , l.platelet_Max
  , l.WBC_min
  , l.WBC_max

  , pf.PaO2FiO2_vent_min

  , uo.UrineOutput

  , gcs.MinGCS
from icustays ie
left join pafi2 pf
 on ie.icustay_id = pf.icustay_id
left join vitalsfirstday v
  on ie.icustay_id = v.icustay_id
left join labsfirstday l
  on ie.icustay_id = l.icustay_id
left join uofirstday uo
  on ie.icustay_id = uo.icustay_id
left join gcsfirstday gcs
  on ie.icustay_id = gcs.icustay_id
)
, scorecalc as
(
  -- Calculate the final score
  -- note that if the underlying data is missing, the component is null
  -- eventually these are treated as 0 (normal), but knowing when data is missing is useful for debugging
  select icustay_id
  -- Respiration
  , case
      when PaO2FiO2_vent_min  <  150 then 3
      when PaO2FiO2_vent_min  >= 150 then 1
      when PaO2FiO2_vent_min is null then null
      else 0
    end as respiration

  -- Coagulation
  , case
  	  when  wbc_min <  1.0 then 3
  	  when (wbc_min >= 1.0 and wbc_min < 2.5) or wbc_max >= 50.0 then 1
      when  platelet_max >= 50.0 then 1
      when  coalesce(platelet_max, wbc_min, wbc_max) is null then null
      else 0
    end as coagulation

  -- Liver / Hepatic
  , case
      -- Bilirubin checks in mg/dL
        when Bilirubin_Max >= 2.0 then 1
        when PT_Max > 3.0 then 1
        when coalesce(Bilirubin_Max, PT_Max) is null then null
        else 0
      end as liver

  -- Cardiovascular
  , case
      when (SysBP_Min <  40 or HeartRate_Min < 30) then 5
      when  SysBP_Max >= 270 then 5
      when (SysBP_Min >= 40 and SysBP_Min < 70) then 3
      when (SysBP_Max >= 240 and SysBP_Max < 270) or HeartRate_Max >= 140 then 1
      when (SysBP_Min >= 70 and SysBP_Min < 90) then 1
      when coalesce(SysBP_Min, SysBP_Max, HeartRate_Min, HeartRate_Max) is null then null
      else 0
    end as cardiovascular

  -- Neurological failure (GCS)
  , case
      when (MinGCS >= 3 and MinGCS <= 5) then 5
      when  MinGCS <  3 then 5 -- GCS Not possible to go under 3, but in case of error.
      when (MinGCS >= 6 and MinGCS <= 8) then 3
      when (MinGCS >= 9 and MinGCS <= 13) then 1     
      when  MinGCS is null then null
  else 0 end
    as cns

  -- Renal failure - high blood urea nitrogen or high creatinine or low urine output
  , case
  	when  BUN_Max >= 20 then 5
    when  UrineOutput < 500 then 5
    when  Creatinine_Max >= 1.6 then 3
    when (UrineOutput >= 500 and Creatinine_Max <= 740) or UrineOutput >= 10000 then 3
  	when (BUN_Max >= 10 and BUN_Max < 20) then 3
    when (Creatinine_Max >= 1.20 and Creatinine_Max <= 1.59) then 1
  	when (BUN_Max >= 6 and BUN_Max <10) then 1    
    when coalesce(UrineOutput, Creatinine_Max, BUN_Max) is null then null
  else 0 end
    as renal
  from scorecomp
)
select ie.subject_id, ie.hadm_id, ie.icustay_id
  -- Combine all the scores to get LODS
  -- Impute 0 if the score is missing
  , coalesce(respiration,0)
  + coalesce(coagulation,0)
  + coalesce(liver,0)
  + coalesce(cardiovascular,0)
  + coalesce(cns,0)
  + coalesce(renal,0)
  as LODS
, respiration
, coagulation
, liver
, cardiovascular
, cns
, renal
from icustays ie
left join scorecalc s
  on ie.icustay_id = s.icustay_id
order by ie.icustay_id;
