function admissions = import_admissions(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  ADMISSIONS = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  ADMISSIONS = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  ADMISSIONS = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  admissions = import_admissions("admissions.xlsx", "admissions", [2, 61052]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Feb-2020 15:23:48

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 61052];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":H" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "gender", "admission_age", "ethnicity", "admission_type", "hospital_expire_flag"];
opts.VariableTypes = ["double", "double", "double", "categorical", "double", "categorical", "categorical", "double"];

% Specify variable properties
opts = setvaropts(opts, ["gender", "ethnicity", "admission_type"], "EmptyFieldRule", "auto");

% Import the data
admissions = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":H" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    admissions = [admissions; tb]; %#ok<AGROW>
end

end