function SOFA = import_SOFA(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  SOFA = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  SOFA = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  SOFA = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  SOFA = import_SOFA("SOFA.xlsx", "SOFA", [2, 61533]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Feb-2020 17:37:59

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 61533];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["ICUSTAY_ID", "SOFA"];
opts.VariableTypes = ["double", "double"];

% Import the data
SOFA = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    SOFA = [SOFA; tb]; %#ok<AGROW>
end

end