
-- \set ON_ERROR_STOP 1

CREATE SCHEMA mimic_testschema;
SET search_path TO mimiciii;

CREATE TABLE mimic_test
   (	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT,
	ICUSTAY_ID INT,
	CHARTTIME TIMESTAMP(0),
	ITEMID INT,
	VALUE DOUBLE PRECISION,
	VALUEUOM VARCHAR(30),
	STORETIME TIMESTAMP(0),
	CGID INT,
	STOPPED VARCHAR(30),
	NEWBOTTLE CHAR(1),
	ISERROR INT,
	CONSTRAINT mimic_test_rowid_pk PRIMARY KEY (ROW_ID)
   ) ;

-- \set outputs_csv :mimic_data_dir 'ERROROUTPUTEVENTS_DATA_TABLE.csv'

-- COPY mimic_test FROM :'outputs_csv' DELIMITER ',' CSV HEADER;

DROP TABLE mimic_test;
DROP SCHEMA mimic_testschema CASCADE;