-- Creates the MIMIC-III derived concepts in DuckDB.
-- Source tables are referenced using the mimiciii schema, and derived tables
-- are created in the mimiciii_derived schema; both schemas must exist.

-- dependencies
.print 'echo_data.sql'
.read echo_data.sql
.print 'durations/weight_durations.sql'
.read durations/weight_durations.sql

-- top-level concepts
.print 'code_status.sql'
.read code_status.sql
.print 'rrt.sql'
.read rrt.sql

-- demographics
.print 'demographics/heightweight.sql'
.read demographics/heightweight.sql
.print 'demographics/icustay_detail.sql'
.read demographics/icustay_detail.sql
.print 'demographics/icustay_times.sql'
.read demographics/icustay_times.sql
.print 'demographics/icustay_hours.sql'
.read demographics/icustay_hours.sql

-- durations
.print 'durations/adenosine_durations.sql'
.read durations/adenosine_durations.sql
.print 'durations/arterial_line_durations.sql'
.read durations/arterial_line_durations.sql
.print 'durations/central_line_durations.sql'
.read durations/central_line_durations.sql
.print 'durations/crrt_durations.sql'
.read durations/crrt_durations.sql
.print 'durations/dobutamine_dose.sql'
.read durations/dobutamine_dose.sql
.print 'durations/dobutamine_durations.sql'
.read durations/dobutamine_durations.sql
.print 'durations/dopamine_dose.sql'
.read durations/dopamine_dose.sql
.print 'durations/dopamine_durations.sql'
.read durations/dopamine_durations.sql
.print 'durations/epinephrine_dose.sql'
.read durations/epinephrine_dose.sql
.print 'durations/epinephrine_durations.sql'
.read durations/epinephrine_durations.sql
.print 'durations/isuprel_durations.sql'
.read durations/isuprel_durations.sql
.print 'durations/milrinone_durations.sql'
.read durations/milrinone_durations.sql
.print 'durations/neuroblock_dose.sql'
.read durations/neuroblock_dose.sql
.print 'durations/norepinephrine_dose.sql'
.read durations/norepinephrine_dose.sql
.print 'durations/norepinephrine_durations.sql'
.read durations/norepinephrine_durations.sql
.print 'durations/phenylephrine_dose.sql'
.read durations/phenylephrine_dose.sql
.print 'durations/phenylephrine_durations.sql'
.read durations/phenylephrine_durations.sql
.print 'durations/vasopressin_dose.sql'
.read durations/vasopressin_dose.sql
.print 'durations/vasopressin_durations.sql'
.read durations/vasopressin_durations.sql
.print 'durations/vasopressor_durations.sql'
.read durations/vasopressor_durations.sql
.print 'durations/ventilation_classification.sql'
.read durations/ventilation_classification.sql
.print 'durations/ventilation_durations.sql'
.read durations/ventilation_durations.sql

-- pivot
.print 'pivot/pivoted_bg.sql'
.read pivot/pivoted_bg.sql
.print 'pivot/pivoted_fio2.sql'
.read pivot/pivoted_fio2.sql
.print 'pivot/pivoted_gcs.sql'
.read pivot/pivoted_gcs.sql
.print 'pivot/pivoted_height.sql'
.read pivot/pivoted_height.sql
.print 'pivot/pivoted_icp.sql'
.read pivot/pivoted_icp.sql
.print 'pivot/pivoted_invasive_lines.sql'
.read pivot/pivoted_invasive_lines.sql
.print 'pivot/pivoted_lab.sql'
.read pivot/pivoted_lab.sql
.print 'pivot/pivoted_rrt.sql'
.read pivot/pivoted_rrt.sql
.print 'pivot/pivoted_uo.sql'
.read pivot/pivoted_uo.sql
.print 'pivot/pivoted_vital.sql'
.read pivot/pivoted_vital.sql
.print 'pivot/pivoted_bg_art.sql'
.read pivot/pivoted_bg_art.sql
.print 'pivot/pivoted_oasis.sql'
.read pivot/pivoted_oasis.sql
.print 'pivot/pivoted_sofa.sql'
.read pivot/pivoted_sofa.sql

-- comorbidity
.print 'comorbidity/elixhauser_ahrq_v37.sql'
.read comorbidity/elixhauser_ahrq_v37.sql
.print 'comorbidity/elixhauser_ahrq_v37_no_drg.sql'
.read comorbidity/elixhauser_ahrq_v37_no_drg.sql
.print 'comorbidity/elixhauser_quan.sql'
.read comorbidity/elixhauser_quan.sql
.print 'comorbidity/elixhauser_score_ahrq.sql'
.read comorbidity/elixhauser_score_ahrq.sql
.print 'comorbidity/elixhauser_score_quan.sql'
.read comorbidity/elixhauser_score_quan.sql

-- firstday
.print 'firstday/blood_gas_first_day.sql'
.read firstday/blood_gas_first_day.sql
.print 'firstday/gcs_first_day.sql'
.read firstday/gcs_first_day.sql
.print 'firstday/height_first_day.sql'
.read firstday/height_first_day.sql
.print 'firstday/labs_first_day.sql'
.read firstday/labs_first_day.sql
.print 'firstday/rrt_first_day.sql'
.read firstday/rrt_first_day.sql
.print 'firstday/urine_output_first_day.sql'
.read firstday/urine_output_first_day.sql
.print 'firstday/ventilation_first_day.sql'
.read firstday/ventilation_first_day.sql
.print 'firstday/vitals_first_day.sql'
.read firstday/vitals_first_day.sql
.print 'firstday/weight_first_day.sql'
.read firstday/weight_first_day.sql
.print 'firstday/blood_gas_first_day_arterial.sql'
.read firstday/blood_gas_first_day_arterial.sql

-- fluid_balance
.print 'fluid_balance/colloid_bolus.sql'
.read fluid_balance/colloid_bolus.sql
.print 'fluid_balance/crystalloid_bolus.sql'
.read fluid_balance/crystalloid_bolus.sql
.print 'fluid_balance/ffp_transfusion.sql'
.read fluid_balance/ffp_transfusion.sql
.print 'fluid_balance/rbc_transfusion.sql'
.read fluid_balance/rbc_transfusion.sql
.print 'fluid_balance/urine_output.sql'
.read fluid_balance/urine_output.sql

-- sepsis
.print 'sepsis/angus.sql'
.read sepsis/angus.sql
.print 'sepsis/explicit.sql'
.read sepsis/explicit.sql
.print 'sepsis/martin.sql'
.read sepsis/martin.sql

-- diagnosis
.print 'diagnosis/ccs_multi_dx.sql'
.read diagnosis/ccs_multi_dx.sql
.print 'diagnosis/ccs_dx.sql'
.read diagnosis/ccs_dx.sql

-- organfailure
.print 'organfailure/kdigo_creatinine.sql'
.read organfailure/kdigo_creatinine.sql
.print 'organfailure/kdigo_uo.sql'
.read organfailure/kdigo_uo.sql
.print 'organfailure/meld.sql'
.read organfailure/meld.sql
.print 'organfailure/kdigo_stages.sql'
.read organfailure/kdigo_stages.sql
.print 'organfailure/kdigo_stages_48hr.sql'
.read organfailure/kdigo_stages_48hr.sql
.print 'organfailure/kdigo_stages_7day.sql'
.read organfailure/kdigo_stages_7day.sql

-- severityscores
.print 'severityscores/apsiii.sql'
.read severityscores/apsiii.sql
.print 'severityscores/lods.sql'
.read severityscores/lods.sql
.print 'severityscores/mlods.sql'
.read severityscores/mlods.sql
.print 'severityscores/oasis.sql'
.read severityscores/oasis.sql
.print 'severityscores/qsofa.sql'
.read severityscores/qsofa.sql
.print 'severityscores/saps.sql'
.read severityscores/saps.sql
.print 'severityscores/sapsii.sql'
.read severityscores/sapsii.sql
.print 'severityscores/sirs.sql'
.read severityscores/sirs.sql
.print 'severityscores/sofa.sql'
.read severityscores/sofa.sql

-- treatment
.print 'treatment/abx_prescriptions_list.sql'
.read treatment/abx_prescriptions_list.sql
.print 'treatment/suspicion_of_infection.sql'
.read treatment/suspicion_of_infection.sql
