-- ----------------------------------------------------------------
--
-- This is a script to add the MIMIC-IV indexes for Postgres.
--
-- This script assumes that the three seperate portions of MIMIC-IV
-- are housed in the same Postgres SQL database under the three 
-- different schemas: mimic_core, mimic_hosp, and mimic_icu.
-- 
-- If you're environment is configured differentially modify the
-- statements that set search_path below.
--
-- ----------------------------------------------------------------

--------------------------
-- MIMIC_CORE
--------------------------
SET search_path TO 'mimic_core';

-------------
-- ADMISSIONS
-------------

DROP INDEX IF EXISTS ADMISSIONS_idx01;
CREATE INDEX ADMISSIONS_IDX01
  ON ADMISSIONS (SUBJECT_ID);

DROP INDEX IF EXISTS ADMISSIONS_idx02;
CREATE INDEX ADMISSIONS_IDX02
  ON ADMISSIONS (HADM_ID);

-------------
-- PATIENTS
-------------

DROP INDEX IF EXISTS PATIENTS_idx01;
CREATE INDEX PATIENTS_IDX01
  ON PATIENTS (SUBJECT_ID);

-------------
-- TRANSFERS
-------------

DROP INDEX IF EXISTS TRANSFERS_idx01;
CREATE INDEX TRANSFERS_IDX01
  ON TRANSFERS (SUBJECT_ID);

DROP INDEX IF EXISTS TRANSFERS_idx02;
CREATE INDEX TRANSFERS_IDX02
  ON TRANSFERS (HADM_ID);

--------------------------
-- MIMIC_HOSP
--------------------------
SET search_path TO 'mimic_hosp';

-------------
-- D_HCPCS
-------------
DROP INDEX IF EXISTS D_HCPCS_idx01;
CREATE INDEX D_HCPCS_IDX01
  ON D_HCPCS (CODE);

--------------------
-- D_ICD_DIAGNOSES
--------------------

DROP INDEX IF EXISTS D_ICD_DIAG_idx01;
CREATE INDEX D_ICD_DIAG_idx01
  ON D_ICD_DIAGNOSES (ICD_CODE);

DROP INDEX IF EXISTS D_ICD_DIAG_idx02;
CREATE INDEX D_ICD_DIAG_idx02
  ON D_ICD_DIAGNOSES (LONG_TITLE);

--------------------
-- D_ICD_PROCEDURES
--------------------

DROP INDEX IF EXISTS D_ICD_PROC_idx01;
CREATE INDEX D_ICD_PROC_idx01
  ON D_ICD_PROCEDURES (ICD_CODE);

DROP INDEX IF EXISTS D_ICD_PROC_idx02;
CREATE INDEX D_ICD_PROC_idx02
  ON D_ICD_PROCEDURES (LONG_TITLE);

  ---------------
  -- D_LABITEMS
  ---------------

  DROP INDEX IF EXISTS D_LABITEMS_idx01;
  CREATE INDEX D_LABITEMS_idx01
    ON D_LABITEMS (ITEMID);

  DROP INDEX IF EXISTS D_LABITEMS_idx02;
  CREATE INDEX D_LABITEMS_idx02
    ON D_LABITEMS (LABEL);

  DROP INDEX IF EXISTS D_LABITEMS_idx03;
  CREATE INDEX D_LABITEMS_idx03
    ON D_LABITEMS (LOINC_CODE);

------------------
-- DIAGNOSES_ICD
------------------

DROP INDEX IF EXISTS DIAGNOSES_ICD_idx01;
CREATE INDEX DIAGNOSES_ICD_idx01
  ON DIAGNOSES_ICD (SUBJECT_ID);

DROP INDEX IF EXISTS DIAGNOSES_ICD_idx02;
CREATE INDEX DIAGNOSES_ICD_idx02
  ON DIAGNOSES_ICD (ICD_CODE);

DROP INDEX IF EXISTS DIAGNOSES_ICD_idx03;
CREATE INDEX DIAGNOSES_ICD_idx03
  ON DIAGNOSES_ICD (HADM_ID);

--------------
-- DRGCODES
--------------

DROP INDEX IF EXISTS DRGCODES_idx01;
CREATE INDEX DRGCODES_idx01
  ON DRGCODES (SUBJECT_ID);

DROP INDEX IF EXISTS DRGCODES_idx02;
CREATE INDEX DRGCODES_idx02
  ON DRGCODES (DRG_CODE);

DROP INDEX IF EXISTS DRGCODES_idx03;
CREATE INDEX DRGCODES_idx03
  ON DRGCODES (DESCRIPTION);

--------------
-- EMAR
--------------

DROP INDEX IF EXISTS EMAR_idx01;
CREATE INDEX EMAR_idx01
  ON EMAR (SUBJECT_ID);

DROP INDEX IF EXISTS EMAR_idx02;
CREATE INDEX EMAR_idx02
  ON EMAR (HADM_ID);

DROP INDEX IF EXISTS EMAR_idx03;
CREATE INDEX EMAR_idx03
  ON EMAR (EMAR_ID);

--------------
-- EMAR_DETAIL
--------------

DROP INDEX IF EXISTS EMAR_DET_idx01;
CREATE INDEX EMAR_DET_idx01
  ON EMAR_DETAIL (SUBJECT_ID);

DROP INDEX IF EXISTS EMAR_DET_idx02;
CREATE INDEX EMAR_DET_idx02
  ON EMAR_DETAIL (EMAR_ID);

DROP INDEX IF EXISTS EMAR_DET_idx03;
CREATE INDEX EMAR_DET_idx03
  ON EMAR_DETAIL(PHARMACY_ID);

DROP INDEX IF EXISTS EMAR_DET_idx04;
CREATE INDEX EMAR_DET_idx04
  ON EMAR_DETAIL (PRODUCT_DESCRIPTION);

--------------
-- HCPCSEVENTS
--------------

DROP INDEX IF EXISTS HCPCSEVENTS_idx01;
CREATE INDEX HCPCSEVENTS_idx01
  ON HCPCSEVENTS (SUBJECT_ID);

DROP INDEX IF EXISTS HCPCSEVENTS_idx02;
CREATE INDEX HCPCSEVENTS_idx02
  ON HCPCSEVENTS (HADM_ID);

DROP INDEX IF EXISTS HCPCSEVENTS_idx03;
CREATE INDEX HCPCSEVENTS_idx03
  ON HCPCSEVENTS (HCPCS_CD);

DROP INDEX IF EXISTS HCPCSEVENTS_idx04;
CREATE INDEX HCPCSEVENTS_idx04
  ON HCPCSEVENTS (SHORT_DESCRIPTION);

--------------
-- LABEVENTS
--------------

DROP INDEX IF EXISTS LABEVENTS_idx01;
CREATE INDEX LABEVENTS_idx01
  ON LABEVENTS (SUBJECT_ID);

DROP INDEX IF EXISTS LABEVENTS_idx02;
CREATE INDEX LABEVENTS_idx02
  ON LABEVENTS (HADM_ID);

DROP INDEX IF EXISTS LABEVENTS_idx03;
CREATE INDEX LABEVENTS_idx03
  ON LABEVENTS (ITEMID);

---------------------
-- MICROBIOLOGYEVENTS
---------------------

DROP INDEX IF EXISTS MICROBIOLOGYEVENTS_idx01;
CREATE INDEX MICROBIOLOGYEVENTS_idx01
  ON MICROBIOLOGYEVENTS (SUBJECT_ID);

DROP INDEX IF EXISTS MICROBIOLOGYEVENTS_idx02;
CREATE INDEX MICROBIOLOGYEVENTS_idx02
  ON MICROBIOLOGYEVENTS (HADM_ID);

DROP INDEX IF EXISTS MICROBIOLOGYEVENTS_idx03;
CREATE INDEX MICROBIOLOGYEVENTS_idx03
  ON MICROBIOLOGYEVENTS (MICROEVENT_ID);

--------------
-- PHARMACY
--------------

DROP INDEX IF EXISTS PHARMACY_idx01;
CREATE INDEX PHARMACY_idx01
  ON PHARMACY (SUBJECT_ID);

DROP INDEX IF EXISTS PHARMACY_idx02;
CREATE INDEX PHARMACY_idx02
  ON PHARMACY (HADM_ID);

DROP INDEX IF EXISTS PHARMACY_idx03;
CREATE INDEX PHARMACY_idx03
  ON PHARMACY (PHARMACY_ID);

DROP INDEX IF EXISTS PHARMACY_idx04;
CREATE INDEX PHARMACY_idx04
  ON PHARMACY (POE_ID);

--------------
-- POE
--------------

DROP INDEX IF EXISTS POE_idx01;
CREATE INDEX POE_idx01
  ON POE (SUBJECT_ID);

DROP INDEX IF EXISTS POE_idx02;
CREATE INDEX POE_idx02
  ON POE (HADM_ID);

DROP INDEX IF EXISTS POE_idx03;
CREATE INDEX POE_idx03
  ON POE (POE_ID);

--------------
-- POE_DETAIL
--------------

DROP INDEX IF EXISTS POE_DET_idx01;
CREATE INDEX POE_DET_idx01
  ON POE_DETAIL (SUBJECT_ID);

DROP INDEX IF EXISTS POE_DET_idx02;
CREATE INDEX POE_DET_idx02
  ON POE_DETAIL (POE_ID);

--------------
-- PRESCRIPTION
--------------

DROP INDEX IF EXISTS PRESCRIPTION_idx01;
CREATE INDEX PRESCRIPTION_idx01
  ON PRESCRIPTION (SUBJECT_ID);

DROP INDEX IF EXISTS PRESCRIPTION_idx02;
CREATE INDEX PRESCRIPTION_idx02
  ON PRESCRIPTION (HADM_ID);

DROP INDEX IF EXISTS PRESCRIPTION_idx03;
CREATE INDEX PRESCRIPTION_idx03
  ON PRESCRIPTION (PHARMACY_ID);

DROP INDEX IF EXISTS PRESCRIPTION_idx04;
CREATE INDEX PRESCRIPTION_idx04
  ON PRESCRIPTION (DRUG);

------------------
-- PROCEDURES_ICD
------------------

DROP INDEX IF EXISTS PROCEDURES_ICD_idx01;
CREATE INDEX PROCEDURES_ICD_idx01
  ON PROCEDURES_ICD (SUBJECT_ID);

DROP INDEX IF EXISTS PROCEDURES_ICD_idx02;
CREATE INDEX PROCEDURES_ICD_idx02
  ON PROCEDURES_ICD (ICD_CODE);

DROP INDEX IF EXISTS PROCEDURES_ICD_idx03;
CREATE INDEX PROCEDURES_ICD_idx03
  ON PROCEDURES_ICD (HADM_ID);

------------------
-- SERVICES
------------------

DROP INDEX IF EXISTS SERVICES_idx01;
CREATE INDEX SERVICES_idx01
  ON SERVICES (SUBJECT_ID);

DROP INDEX IF EXISTS SERVICES_idx02;
CREATE INDEX SERVICES_idx02
  ON SERVICES (HADM_ID);

--------------------------
-- MIMIC_ICU
--------------------------
SET search_path TO 'mimic_icu';

------------------
-- CHARTEVENTS
------------------

DROP INDEX IF EXISTS CHARTEVENTS_idx01;
CREATE INDEX CHARTEVENTS_idx01 
  ON CHARTEVENTS (ITEMID);

DROP INDEX IF EXISTS CHARTEVENTS_idx02;
CREATE INDEX CHARTEVENTS_idx02 
  ON CHARTEVENTS (SUBJECT_ID);

DROP INDEX IF EXISTS CHARTEVENTS_idx03;
CREATE INDEX CHARTEVENTS_idx03
  ON CHARTEVENTS (HADM_ID);

DROP INDEX IF EXISTS CHARTEVENTS_idx04;
CREATE INDEX CHARTEVENTS_idx04
  ON CHARTEVENTS (STAY_ID);

-----------
-- D_ITEMS
-----------

DROP INDEX IF EXISTS D_ITEMS_idx01;
CREATE INDEX D_ITEMS_idx01
  ON D_ITEMS (ITEMID);

DROP INDEX IF EXISTS D_ITEMS_idx02;
CREATE INDEX D_ITEMS_idx02
  ON D_ITEMS (LABEL);

-------------------
-- DATETIMEEVENTS
-------------------

DROP INDEX IF EXISTS DATETIMEEVENTS_idx01;
CREATE INDEX DATETIMEEVENTS_idx01
  ON DATETIMEEVENTS (SUBJECT_ID);

DROP INDEX IF EXISTS DATETIMEEVENTS_idx02;
CREATE INDEX DATETIMEEVENTS_idx02
  ON DATETIMEEVENTS (ITEMID);

DROP INDEX IF EXISTS DATETIMEEVENTS_idx03;
CREATE INDEX DATETIMEEVENTS_idx03
  ON DATETIMEEVENTS (ICUSTAY_ID);

DROP INDEX IF EXISTS DATETIMEEVENTS_idx04;
CREATE INDEX DATETIMEEVENTS_idx04
  ON DATETIMEEVENTS (HADM_ID);

------------------
-- ICUSTAYS
------------------

DROP INDEX IF EXISTS ICUSTAYS_idx01;
CREATE INDEX ICUSTAYS_idx01
  ON ICUSTAYS (SUBJECT_ID);

DROP INDEX IF EXISTS ICUSTAYS_idx02;
CREATE INDEX ICUSTAYS_idx02
  ON ICUSTAYS (STAY_ID);

DROP INDEX IF EXISTS ICUSTAYS_idx03;
CREATE INDEX ICUSTAYS_IDX06
  ON ICUSTAYS (HADM_ID);

--------------
-- INPUTEVENTS
--------------

DROP INDEX IF EXISTS INPUTEVENTS_idx01;
CREATE INDEX INPUTEVENTS_idx01
  ON INPUTEVENTS (SUBJECT_ID);

DROP INDEX IF EXISTS INPUTEVENTS_idx02;
CREATE INDEX INPUTEVENTS_idx02
  ON INPUTEVENTS (HADM_ID);

DROP INDEX IF EXISTS INPUTEVENTS_idx03;
CREATE INDEX INPUTEVENTS_idx03
  ON INPUTEVENTS (STAY_ID);

DROP INDEX IF EXISTS INPUTEVENTS_idx04;
CREATE INDEX INPUTEVENTS_idx04
  ON INPUTEVENTS (ENDTIME, STARTTIME);

DROP INDEX IF EXISTS INPUTEVENTS_idx05;
CREATE INDEX INPUTEVENTS_idx05
  ON INPUTEVENTS(ITEMID);

---------------
-- OUTPUTEVENTS
---------------
DROP INDEX IF EXISTS OUTPUTEVENTS_idx01;
CREATE INDEX OUTPUTEVENTS_idx01
  ON OUTPUTEVENTS (SUBJECT_ID);

DROP INDEX IF EXISTS OUTPUTEVENTS_idx02;
CREATE INDEX OUTPUTEVENTS_idx02
  ON OUTPUTEVENTS (ITEMID);

DROP INDEX IF EXISTS OUTPUTEVENTS_idx03;
CREATE INDEX OUTPUTEVENTS_idx03
  ON OUTPUTEVENTS (STAY_ID);

DROP INDEX IF EXISTS OUTPUTEVENTS_idx04;
CREATE INDEX OUTPUTEVENTS_idx04
  ON OUTPUTEVENTS (HADM_ID);

---------------------
-- PROCEDUREEVENTS
---------------------

DROP INDEX IF EXISTS PROCEDUREEVENTS_idx01;
CREATE INDEX PROCEDUREEVENTS_idx01
  ON PROCEDUREEVENTS (SUBJECT_ID);

DROP INDEX IF EXISTS PROCEDUREEVENTS_idx02;
CREATE INDEX PROCEDUREEVENTS_idx02
  ON PROCEDUREEVENTS (HADM_ID);

DROP INDEX IF EXISTS PROCEDUREEVENTS_idx03;
CREATE INDEX PROCEDUREEVENTS_idx03
  ON PROCEDUREEVENTS (STAY_ID);

DROP INDEX IF EXISTS PROCEDUREEVENTS_idx04;
CREATE INDEX PROCEDUREEVENTS_idx04
  ON PROCEDUREEVENTS (ITEMID);