-------------
-- ADMISSIONS
-------------

drop index MIMICIII.ADMISSIONS_idx01;
CREATE INDEX ADMISSIONS_IDX01 
  ON MIMICIII.ADMISSIONS (SUBJECT_ID,HADM_ID);

drop index MIMICIII.ADMISSIONS_idx02;
CREATE INDEX ADMISSIONS_IDX02 
  ON MIMICIII.ADMISSIONS (ADMITTIME, DISCHTIME, DEATHTIME);

drop index MIMICIII.ADMISSIONS_idx03;
CREATE INDEX ADMISSIONS_IDX03
  ON MIMICIII.ADMISSIONS (ADMISSION_TYPE);


-----------
--CALLOUT--
-----------

drop index MIMICIII.CALLOUT_idx01;
CREATE INDEX CALLOUT_IDX01
  ON MIMICIII.CALLOUT (SUBJECT_ID, HADM_ID);

drop index MIMICIII.CALLOUT_idx02;
CREATE INDEX CALLOUT_IDX02
  ON MIMICIII.CALLOUT (CURR_CAREUNIT);

drop index MIMICIII.CALLOUT_idx03;
CREATE INDEX CALLOUT_IDX03
  ON MIMICIII.CALLOUT (CALLOUT_SERVICE);

drop index MIMICIII.CALLOUT_idx04;
CREATE INDEX CALLOUT_IDX04
  ON MIMICIII.CALLOUT (CURR_WARDID, CALLOUT_WARDID, 
    DISCHARGE_WARDID);

drop index MIMICIII.CALLOUT_idx05;
CREATE INDEX CALLOUT_IDX05
  ON MIMICIII.CALLOUT (CALLOUT_STATUS, 
    CALLOUT_OUTCOME);

drop index MIMICIII.CALLOUT_idx06;
CREATE INDEX CALLOUT_IDX06
  ON MIMICIII.CALLOUT (CREATETIME, UPDATETIME, 
    ACKNOWLEDGETIME, OUTCOMETIME);

---------------
-- CAREGIVERS
---------------

drop index MIMICIII.CAREGIVERS_idx01;
CREATE INDEX CAREGIVERS_IDX01
  ON MIMICIII.CAREGIVERS (CGID, LABEL);

---------------
-- CHARTEVENTS
---------------
drop index MIMICIII.CHARTEVENTS_idx01;
CREATE INDEX CHARTEVENTS_idx01 
  ON MIMICIII.CHARTEVENTS (SUBJECT_ID, HADM_ID, ICUSTAY_ID);


drop index MIMICIII.CHARTEVENTS_idx02;
CREATE INDEX CHARTEVENTS_idx02 
  ON MIMICIII.CHARTEVENTS (ITEMID);


drop index MIMICIII.CHARTEVENTS_idx03;
CREATE INDEX CHARTEVENTS_idx03 
  ON MIMICIII.CHARTEVENTS (CHARTTIME, STORETIME);


drop index MIMICIII.CHARTEVENTS_idx04;
CREATE INDEX CHARTEVENTS_idx04 
  ON MIMICIII.CHARTEVENTS (CGID);

drop index MIMICIII.CHARTEVENTS_idx05;
CREATE INDEX CHARTEVENTS_idx05 
  ON MIMICIII.CHARTEVENTS (VALUE);

---------------
-- CPTEVENTS
---------------

drop index MIMICIII.CPTEVENTS_idx01;
CREATE INDEX CPTEVENTS_idx01 
  ON MIMICIII.CPTEVENTS (SUBJECT_ID, HADM_ID);

drop index MIMICIII.CPTEVENTS_idx02;
CREATE INDEX CPTEVENTS_idx02 
  ON MIMICIII.CPTEVENTS (CPT_CD, TICKET_ID_SEQ);

-----------
-- D_CPT
-----------

-- Table is 134 rows - doesn't need an index.

--------------------
-- D_ICD_DIAGNOSES
--------------------

drop index MIMICIII.D_ICD_DIAG_idx01;
CREATE INDEX D_ICD_DIAG_idx01 
  ON MIMICIII.D_ICD_DIAGNOSES (ICD9_CODE, DIAG_OR_PROC);

drop index MIMICIII.D_ICD_DIAG_idx02;
CREATE INDEX D_ICD_DIAG_idx02 
  ON MIMICIII.D_ICD_DIAGNOSES (SHORT_TITLE, LONG_TITLE);

--------------------
-- D_ICD_PROCEDURES
--------------------

drop index MIMICIII.D_ICD_PROC_idx01;
CREATE INDEX D_ICD_PROC_idx01 
  ON MIMICIII.D_ICD_PROCEDURES (ICD9_CODE, DIAG_OR_PROC);

drop index MIMICIII.D_ICD_PROC_idx02;
CREATE INDEX D_ICD_PROC_idx02 
  ON MIMICIII.D_ICD_PROCEDURES (SHORT_TITLE, LONG_TITLE);

-----------
-- D_ITEMS
-----------

drop index MIMICIII.D_ITEMS_idx01;
CREATE INDEX D_ITEMS_idx01 
  ON MIMICIII.D_ITEMS (ITEMID);

drop index MIMICIII.D_ITEMS_idx02;
CREATE INDEX D_ITEMS_idx02 
  ON MIMICIII.D_ITEMS (LABEL, DBSOURCE);

drop index MIMICIII.D_ITEMS_idx03;
CREATE INDEX D_ITEMS_idx03 
  ON MIMICIII.D_ITEMS (CATEGORY);

---------------
-- D_LABITEMS
---------------

drop index MIMICIII.D_LABITEMS_idx01;
CREATE INDEX D_LABITEMS_idx01 
  ON MIMICIII.D_LABITEMS (ITEMID);

drop index MIMICIII.D_LABITEMS_idx02;
CREATE INDEX D_LABITEMS_idx02
  ON MIMICIII.D_LABITEMS (LABEL, FLUID, CATEGORY);

drop index MIMICIII.D_LABITEMS_idx03;
CREATE INDEX D_LABITEMS_idx03 
  ON MIMICIII.D_LABITEMS (LOINC_CODE);

-------------------
-- DATETIMEEVENTS
-------------------

drop index MIMICIII.DATETIMEEVENTS_idx01;
CREATE INDEX DATETIMEEVENTS_idx01 
  ON MIMICIII.DATETIMEEVENTS (SUBJECT_ID, 
    HADM_ID, ICUSTAY_ID);

drop index MIMICIII.DATETIMEEVENTS_idx02;
CREATE INDEX DATETIMEEVENTS_idx02 
  ON MIMICIII.DATETIMEEVENTS (ITEMID);

drop index MIMICIII.DATETIMEEVENTS_idx03;
CREATE INDEX DATETIMEEVENTS_idx03 
  ON MIMICIII.DATETIMEEVENTS (CHARTTIME);

drop index MIMICIII.DATETIMEEVENTS_idx04;
CREATE INDEX DATETIMEEVENTS_idx04 
  ON MIMICIII.DATETIMEEVENTS (CGID);

drop index MIMICIII.DATETIMEEVENTS_idx05;
CREATE INDEX DATETIMEEVENTS_idx05 
  ON MIMICIII.DATETIMEEVENTS (VALUE);

------------------
-- DIAGNOSES_ICD
------------------

drop index MIMICIII.DIAGNOSES_ICD_idx01;
CREATE INDEX DIAGNOSES_ICD_idx01 
  ON MIMICIII.DIAGNOSES_ICD (SUBJECT_ID, HADM_ID);

drop index MIMICIII.DIAGNOSES_ICD_idx02;
CREATE INDEX DIAGNOSES_ICD_idx02 
  ON MIMICIII.DIAGNOSES_ICD (ICD9_CODE, SEQUENCE);

drop index MIMICIII.DIAGNOSES_ICD_idx03;
CREATE INDEX DIAGNOSES_ICD_idx03 
  ON MIMICIII.DIAGNOSES_ICD (DESCRIPTION);

--------------
-- DRGCODES
--------------

drop index MIMICIII.DRGCODES_idx01;
CREATE INDEX DRGCODES_idx01 
  ON MIMICIII.DRGCODES (SUBJECT_ID, HADM_ID);

drop index MIMICIII.DRGCODES_idx02;
CREATE INDEX DRGCODES_idx02 
  ON MIMICIII.DRGCODES (DRG_CODE, DRG_TYPE);

drop index MIMICIII.DRGCODES_idx03;
CREATE INDEX DRGCODES_idx03 
  ON MIMICIII.DRGCODES (DESCRIPTION, DRG_SEVERITY);

------------------
-- ICUSTAYEVENTS
------------------

drop index MIMICIII.ICUSTAYEVENTS_idx01;
CREATE INDEX ICUSTAYEVENTS_idx01 
  ON MIMICIII.ICUSTAYEVENTS (SUBJECT_ID, HADM_ID);

drop index MIMICIII.ICUSTAYEVENTS_idx02;
CREATE INDEX ICUSTAYEVENTS_idx02 
  ON MIMICIII.ICUSTAYEVENTS (ICUSTAY_ID, DBSOURCE);

drop index MIMICIII.ICUSTAYEVENTS_idx03;
CREATE INDEX ICUSTAYEVENTS_idx03 
  ON MIMICIII.ICUSTAYEVENTS (LOS);

drop index MIMICIII.ICUSTAYEVENTS_idx04;
CREATE INDEX ICUSTAYEVENTS_idx04 
  ON MIMICIII.ICUSTAYEVENTS (FIRST_CAREUNIT);

drop index MIMICIII.ICUSTAYEVENTS_idx05;
CREATE INDEX ICUSTAYEVENTS_idx05 
  ON MIMICIII.ICUSTAYEVENTS (LAST_CAREUNIT);

-------------
-- IOEVENTS
-------------

drop index MIMICIII.IOEVENTS_idx01;
CREATE INDEX IOEVENTS_idx01 
  ON MIMICIII.IOEVENTS (SUBJECT_ID, HADM_ID);

drop index MIMICIII.IOEVENTS_idx02;
CREATE INDEX IOEVENTS_idx02 
  ON MIMICIII.IOEVENTS (ICUSTAY_ID);

drop index MIMICIII.IOEVENTS_idx03;
CREATE INDEX IOEVENTS_idx03 
  ON MIMICIII.IOEVENTS (ENDTIME, STARTTIME);

drop index MIMICIII.IOEVENTS_idx04;
CREATE INDEX IOEVENTS_idx04 
  ON MIMICIII.IOEVENTS (ITEMID);

drop index MIMICIII.IOEVENTS_idx05;
CREATE INDEX IOEVENTS_idx05 
  ON MIMICIII.IOEVENTS (RATE);

drop index MIMICIII.IOEVENTS_idx06;
CREATE INDEX IOEVENTS_idx06 
  ON MIMICIII.IOEVENTS (VOLUME);

drop index MIMICIII.IOEVENTS_idx07;
CREATE INDEX IOEVENTS_idx07 
  ON MIMICIII.IOEVENTS (CGID);

drop index MIMICIII.IOEVENTS_idx08;
CREATE INDEX IOEVENTS_idx08 
  ON MIMICIII.IOEVENTS (LINKORDERID, ORDERID);

drop index MIMICIII.IOEVENTS_idx09;
CREATE INDEX IOEVENTS_idx09
  ON MIMICIII.IOEVENTS (ORDERCATEGORYDESCRIPTION, 
    ORDERCATEGORYNAME, SECONDARYORDERCATEGORYNAME);

drop index MIMICIII.IOEVENTS_idx10;
CREATE INDEX IOEVENTS_idx10 
  ON MIMICIII.IOEVENTS (ORDERCOMPONENTTYPEDESCRIPTION, 
    ORDERCATEGORYDESCRIPTION);

--------------
-- LABEVENTS
--------------

drop index MIMICIII.LABEVENTS_idx01;
CREATE INDEX LABEVENTS_idx01 
  ON MIMICIII.LABEVENTS (SUBJECT_ID, HADM_ID);

drop index MIMICIII.LABEVENTS_idx02;
CREATE INDEX LABEVENTS_idx02 
  ON MIMICIII.LABEVENTS (ITEMID);

drop index MIMICIII.LABEVENTS_idx03;
CREATE INDEX LABEVENTS_idx03 
  ON MIMICIII.LABEVENTS (CHARTTIME);

drop index MIMICIII.LABEVENTS_idx04;
CREATE INDEX LABEVENTS_idx04 
  ON MIMICIII.LABEVENTS (VALUE, VALUENUM);

----------------------
-- MICROBIOLOGYEVENTS
----------------------

drop index MIMICIII.MICROBIOLOGYEVENTS_idx01;
CREATE INDEX MICROBIOLOGYEVENTS_idx01 
  ON MIMICIII.MICROBIOLOGYEVENTS (SUBJECT_ID, HADM_ID);

drop index MIMICIII.MICROBIOLOGYEVENTS_idx02;
CREATE INDEX MICROBIOLOGYEVENTS_idx02 
  ON MIMICIII.MICROBIOLOGYEVENTS (CHARTDATE, CHARTTIME);

drop index MIMICIII.MICROBIOLOGYEVENTS_idx03;
CREATE INDEX MICROBIOLOGYEVENTS_idx03 
  ON MIMICIII.MICROBIOLOGYEVENTS (SPEC_ITEMID, 
    ORG_ITEMID, AB_ITEMID);

---------------
-- NOTEEVENTS
---------------

drop index MIMICIII.NOTEEVENTS_idx01;
CREATE INDEX NOTEEVENTS_idx01 
  ON MIMICIII.NOTEEVENTS (SUBJECT_ID, HADM_ID);

drop index MIMICIII.NOTEEVENTS_idx02;
CREATE INDEX NOTEEVENTS_idx02 
  ON MIMICIII.NOTEEVENTS (CHARTDATE);

drop index MIMICIII.NOTEEVENTS_idx03;
CREATE INDEX NOTEEVENTS_idx03 
  ON MIMICIII.NOTEEVENTS (CGID);

drop index MIMICIII.NOTEEVENTS_idx04;
CREATE INDEX NOTEEVENTS_idx04 
  ON MIMICIII.NOTEEVENTS (RECORD_ID);

drop index MIMICIII.NOTEEVENTS_idx05;
CREATE INDEX NOTEEVENTS_idx05 
  ON MIMICIII.NOTEEVENTS (CATEGORY, DESCRIPTION);

-------------
-- PATIENTS
-------------

-- Note that SUBJECT_ID is already indexed as it is unique

drop index MIMICIII.PATIENTS_idx01;
CREATE INDEX PATIENTS_idx01 
  ON MIMICIII.PATIENTS (HOSPITAL_EXPIRE_FLAG);


------------------
-- PRESCRIPTIONS
------------------

drop index MIMICIII.PRESCRIPTIONS_idx01;
CREATE INDEX PRESCRIPTIONS_idx01 
  ON MIMICIII.PRESCRIPTIONS (SUBJECT_ID, HADM_ID);

drop index MIMICIII.PRESCRIPTIONS_idx02;
CREATE INDEX PRESCRIPTIONS_idx02 
  ON MIMICIII.PRESCRIPTIONS (ICUSTAY_ID);

drop index MIMICIII.PRESCRIPTIONS_idx03;
CREATE INDEX PRESCRIPTIONS_idx03 
  ON MIMICIII.PRESCRIPTIONS (DRUG_TYPE);

drop index MIMICIII.PRESCRIPTIONS_idx04;
CREATE INDEX PRESCRIPTIONS_idx04 
  ON MIMICIII.PRESCRIPTIONS (DRUG);

drop index MIMICIII.PRESCRIPTIONS_idx05;
CREATE INDEX PRESCRIPTIONS_idx05
  ON MIMICIII.PRESCRIPTIONS (STARTTIME, ENDTIME);

-------------------
-- PROCEDURES_ICD
-------------------

drop index MIMICIII.PROCEDURES_ICD_idx01;
CREATE INDEX PROCEDURES_ICD_idx01 
  ON MIMICIII.PROCEDURES_ICD (SUBJECT_ID, HADM_ID);

drop index MIMICIII.PROCEDURES_ICD_idx02;
CREATE INDEX PROCEDURES_ICD_idx02 
  ON MIMICIII.PROCEDURES_ICD (ICD9_CODE, PROC_SEQ_NUM);

-------------
-- SERVICES
-------------

drop index MIMICIII.SERVICES_idx01;
CREATE INDEX SERVICES_idx01 
  ON MIMICIII.SERVICES (SUBJECT_ID, HADM_ID);

drop index MIMICIII.SERVICES_idx02;
CREATE INDEX SERVICES_idx02 
  ON MIMICIII.SERVICES (TRANSFERTIME);

drop index MIMICIII.SERVICES_idx03;
CREATE INDEX SERVICES_idx03
  ON MIMICIII.SERVICES (CURR_SERVICE, PREV_SERVICE);

-------------
-- TRANSFERS
-------------

drop index MIMICIII.TRANSFERS_idx01;
CREATE INDEX TRANSFERS_idx01 
  ON MIMICIII.TRANSFERS (SUBJECT_ID, HADM_ID);

drop index MIMICIII.TRANSFERS_idx02;
CREATE INDEX TRANSFERS_idx02 
  ON MIMICIII.TRANSFERS (ICUSTAY_ID);

drop index MIMICIII.TRANSFERS_idx03;
CREATE INDEX TRANSFERS_idx03 
  ON MIMICIII.TRANSFERS (CURR_CAREUNIT, PREV_CAREUNIT);

drop index MIMICIII.TRANSFERS_idx04;
CREATE INDEX TRANSFERS_idx04 
  ON MIMICIII.TRANSFERS (INTIME, OUTTIME);

drop index MIMICIII.TRANSFERS_idx05;
CREATE INDEX TRANSFERS_idx05 
  ON MIMICIII.TRANSFERS (LOS);
