-- THIS SCRIPT IS AUTOMATICALLY GENERATED. DO NOT EDIT IT DIRECTLY.
DROP TABLE IF EXISTS mimiciii_derived.qsofa; CREATE TABLE mimiciii_derived.qsofa AS
/* ------------------------------------------------------------------ */ /* Title: Quick Sequential Organ Failure Assessment (qSOFA) */ /* This query extracts the quick sequential organ failure assessment. */ /* This score was a recent revision of SOFA, aiming to detect patients at risk of sepsis. */ /* The score is calculated on the first day of each ICU patients' stay - though needn't be. */ /* ------------------------------------------------------------------ */ /* Reference for qSOFA: */ /*    Singer M, et al. The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3) */ /*    Seymour CW, et al. Assessment of Clinical Criteria for Sepsis: For the Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3) */ /* Variables used in qSOFA: */ /*  GCS, respiratory rate, systolic blood pressure */ /* The following views required to run this query: */ /*  1) gcsfirstday - generated by gcs-first-day.sql */ /*  2) vitalsfirstday - generated by vitals-first-day.sql */ /* Note: */ /*  The score is calculated for *all* ICU patients, with the assumption that the user will subselect appropriate ICUSTAY_IDs. */ /*  For example, the score is calculated for neonates, but it is likely inappropriate to actually use the score values for these patients. */
WITH scorecomp AS (
  SELECT
    ie.icustay_id,
    v.sysbp_min,
    v.resprate_max,
    gcs.mingcs
  FROM mimiciii.icustays AS ie
  LEFT JOIN mimiciii_derived.vitals_first_day AS v
    ON ie.icustay_id = v.icustay_id
  LEFT JOIN mimiciii_derived.gcs_first_day AS gcs
    ON ie.icustay_id = gcs.icustay_id
), scorecalc AS (
  /* Calculate the final score */ /* note that if the underlying data is missing, the component is null */ /* eventually these are treated as 0 (normal), but knowing when data is missing is useful for debugging */
  SELECT
    icustay_id,
    CASE WHEN sysbp_min IS NULL THEN NULL WHEN sysbp_min <= 100 THEN 1 ELSE 0 END AS sysbp_score,
    CASE WHEN mingcs IS NULL THEN NULL WHEN mingcs <= 13 THEN 1 ELSE 0 END AS gcs_score,
    CASE WHEN resprate_max IS NULL THEN NULL WHEN resprate_max >= 22 THEN 1 ELSE 0 END AS resprate_score
  FROM scorecomp
)
SELECT
  ie.subject_id,
  ie.hadm_id,
  ie.icustay_id,
  COALESCE(sysbp_score, 0) + COALESCE(gcs_score, 0) + COALESCE(resprate_score, 0) AS qsofa,
  sysbp_score,
  gcs_score,
  resprate_score
FROM mimiciii.icustays AS ie
LEFT JOIN scorecalc AS s
  ON ie.icustay_id = s.icustay_id
ORDER BY
  ie.icustay_id NULLS FIRST