OPTIONS (
skip=1,
errors=0,
direct=true,
multithreading=true
)
LOAD DATA
INFILE 'NOTEEVENTS.csv' "str '\n'><><?~`;;`"
BADFILE 'logfile.bad'
DISCARDFILE 'logfile.discard'
APPEND
INTO TABLE noteevents
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING nullcols
(
ROW_ID,
SUBJECT_ID,
HADM_ID,
CHARTDATE DATE "YYYY-MM-DD HH24:MI:SS",
CHARTTIME DATE "YYYY-MM-DD HH24:MI:SS",
STORETIME DATE "YYYY-MM-DD HH24:MI:SS",
CATEGORY,
DESCRIPTION,
CGID,
ISERROR,
TEXT
)
