drop table if exists weight_first_day; create table weight_first_day as 
-- This query extracts weights for adult ICU patients on their first ICU day.
-- It does *not* use any information after the first ICU day, as weight is
-- sometimes used to monitor fluid balance.

-- ** Requires the echodata view, generated by concepts/echo-data.sql

with ce as
(
    select
        c.icustay_id
        -- we take the avg value from roughly first day
        -- TODO: eliminate obvious outliers if there is a reasonable weight
        -- (e.g. weight of 180kg and 90kg would remove 180kg instead of taking the median)
        , avg(valuenum) as weight_admit
    from chartevents c
    inner join icustays ie
        on c.icustay_id = ie.icustay_id
        and c.charttime <= (ie.intime + interval '1 day')
        and c.charttime > (ie.intime - interval '1 day') -- some fuzziness for admit time
    where c.valuenum is not null
        and c.itemid in (762) -- admit wt
        and c.valuenum != 0
        -- exclude rows marked as error
        and (c.error is null or c.error = 0)
    group by c.icustay_id
)
, dwt as
(
    select
        c.icustay_id
        , avg(valuenum) as weight_daily
    from chartevents c
    inner join icustays ie
        on c.icustay_id = ie.icustay_id
        and c.charttime <= (ie.intime + interval '1 day')
        and c.charttime > (ie.intime - interval '1 day') -- some fuzziness for admit time
    where c.valuenum is not null
        and c.itemid in (763) -- daily weight
        and c.valuenum != 0
        -- exclude rows marked as error
        and (c.error is null or c.error = 0)
    group by c.icustay_id
)

select
    ie.icustay_id
    , round(cast(case 
        when ce.icustay_id is not null then ce.weight_admit
        when dwt.icustay_id is not null then dwt.weight_daily
        else null end as numeric), 2)
    as weight
    -- components
    , ce.weight_admit
    , dwt.weight_daily
from icustays ie
-- filter to only adults
inner join patients pat
    on ie.subject_id = pat.subject_id
    and ie.intime > (pat.dob + interval '1 year')
-- admission weight
left join ce
    on ie.icustay_id = ce.icustay_id
-- daily weights
left join dwt
    on ie.icustay_id = dwt.icustay_id
order by ie.icustay_id;