name: chexpert-mimic-cxr
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - decorator=4.3.0
  - docopt=0.6.2
  - intel-openmp=2019.1
  - jpype1=0.6.3
  - libgfortran-ng=7.3.0
  - mkl=2019.1
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - nltk=3.3.0
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pandas=0.23.4
  - ply=3.11
  - python-dateutil=2.7.5
  - pytz=2018.7
  - six=1.11.0
  - tqdm=4.28.1
  - ca-certificates=2018.03.07
  - certifi=2018.11.29
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - networkx=1.11
  - openssl=1.1.1a
  - pip=18.1
  - python=3.6.7
  - readline=7.0
  - setuptools=40.6.2
  - sqlite=3.25.3
  - tk=8.6.8
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - jpype1=0.6.3
  - pip:
    - bioc==1.1.dev3
    - bllipparser==2016.9.11
    - deprecation==2.0.6
    - docutils==0.13.1
    - lxml==3.7.3
    - negbio==0.9.4
    - packaging==18.0
    - pyparsing==2.3.0
    - pystanforddependencies==0.3.1