name: Generate tables on BigQuery

on:
  release:
    types: [released]

env:
  MIMIC_IV_VERSION: 3_1

jobs:
  create-tables:
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'mimic-code@physionet-data.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/569883598760/locations/global/workloadIdentityPools/github/providers/mimic-code'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Run make_concepts
        run: |
            echo "Generating tables on BigQuery"
            cd mimic-iv/concepts
            bash make_concepts.sh
      
      - name: Copy to release specific schema
        run: |
            echo "Copying tables to release specific schema: mimiciv_${MIMIC_IV_VERSION}_derived"
            bash mimic-iv/concepts/copy_concepts_to_versioned_schema.sh ${MIMIC_IV_VERSION}