name: Generate tables on BigQuery

on:
  release:
    types: [published]
    branches: ["main"]

jobs:
  create-tables:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Run make_concepts
        run: |
            echo "Generating tables on BigQuery"
            cd mimic-iv/concepts
            bash make_concepts.sh