name: sqlite demo db build
on:
  pull_request_review:
    types: [submitted]
  # TEMP: test on push to branch
  push:
    branches:
      - alistair/more_gh_action_shenanigans

jobs:
  mimic-iv-sqlite:
    # only run if PR is approved
    # TEMP: also run on push
    if: github.event_name == 'push' || github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    container: python:3.10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python dependencies
        run: |
          pip install pandas

      - name: Download demo data
        uses: ./.github/actions/download-demo

      - name: Load icu/hosp data into SQLite
        run: |
          echo "Running SQLite build."
          python ${BUILDCODE_PATH}/import.py

          echo `md5sum mimic4.db`

        env:
          BUILDCODE_PATH: mimic-iv/buildmimic/sqlite
